const MILLISECOND = 1000

export const VIBRATION_PATTERN = [
    0.5 * MILLISECOND,
    0.5 * MILLISECOND,
    0.5 * MILLISECOND,
    1 * MILLISECOND,
    1 * MILLISECOND,
    1 * MILLISECOND,
    2 * MILLISECOND
]